# Generated by Django 3.1.13 on 2021-09-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_appname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppName',
            new_name='AppNameModel',
        ),
    ]
