# Generated by Django 3.1.13 on 2021-09-26 19:15

import apps.general.users.signals
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.general.users.signals.user_directory_path, verbose_name='Foto de perfil')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Celular')),
                ('names', models.CharField(max_length=50, verbose_name='Nombres')),
                ('surname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('full_name', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Nombres y Apellidos')),
                ('birthday', models.DateField(verbose_name='Fecha de nacimiento')),
                ('age', models.CharField(editable=False, max_length=4, verbose_name='Edad')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sexo')),
                ('privacy', models.BooleanField(default=False, verbose_name='Términos y condiciones')),
                ('newsletter', models.BooleanField(default=False, verbose_name='Recibir más información')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('username', models.CharField(max_length=16, unique=True, verbose_name='Usuario')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['id'],
                'unique_together': {('username', 'email')},
            },
        ),
    ]
