# Generated by Django 3.1.13 on 2021-09-26 19:15

import apps.general.users.signals
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('counter_amount', models.CharField(max_length=8, verbose_name='Cantidad del Contador')),
                ('counter_icon', models.CharField(max_length=50, verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Contador',
                'verbose_name_plural': 'Contadores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InterestsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('interest_icon', models.CharField(max_length=50, verbose_name='Icono')),
                ('interest_icon_color', models.CharField(max_length=50, verbose_name='Color del Icono')),
            ],
            options={
                'verbose_name': 'Interes',
                'verbose_name_plural': 'Intereses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SkillsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('skills_percentage', models.IntegerField(verbose_name='Porcentage de la habilidad')),
            ],
            options={
                'verbose_name': 'Habilida',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('testimonial_work', models.CharField(max_length=50, verbose_name='Ocupación o Profesión')),
                ('testimonial_text', ckeditor.fields.RichTextField(verbose_name='Testimonio')),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.general.users.signals.user_directory_path, verbose_name='Foto de perfil')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Celular')),
                ('names', models.CharField(max_length=50, verbose_name='Nombres')),
                ('surname', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('full_name', models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Nombres y Apellidos')),
                ('birthday', models.DateField(verbose_name='Fecha de nacimiento')),
                ('age', models.CharField(editable=False, max_length=4, verbose_name='Edad')),
                ('gender', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sexo')),
                ('privacy', models.BooleanField(default=False, verbose_name='Términos y condiciones')),
                ('newsletter', models.BooleanField(default=False, verbose_name='Recibir más información')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cración')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('description_1', ckeditor.fields.RichTextField(verbose_name='Descripción 1')),
                ('description_2', ckeditor.fields.RichTextField(verbose_name='Descripción 2')),
                ('web_page', models.CharField(blank=True, max_length=50, null=True, verbose_name='Página Web')),
                ('grade', models.CharField(max_length=30, verbose_name='Grado de educación')),
                ('freelance', models.CharField(max_length=30, verbose_name='Disponibilidad como Freelance')),
                ('strength_1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Fortaleza 1')),
                ('strength_2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Fortaleza 2')),
                ('counters', models.ManyToManyField(to='about.CountersModel')),
                ('interests', models.ManyToManyField(to='about.InterestsModel')),
                ('skills', models.ManyToManyField(to='about.SkillsModel')),
                ('testimonials', models.ManyToManyField(blank=True, to='about.TestimonialModel')),
            ],
            options={
                'verbose_name': 'Información Conóceme',
                'verbose_name_plural': 'Información Conóceme',
                'ordering': ['id'],
                'unique_together': {('phone', 'email')},
            },
        ),
    ]
